PIZZERIA.APP/Models/IngredienteViewModel.cs
namespace PIZZERIA.APP.Models
{
    public class IngredienteViewModel
    {
        public int IngredienteId { get; set; }
        public string Denominacion { get; set; } = String.Empty;
    }
}

PIZZERIA.APP/Models/PedidoViewModel.cs
using PIZZERIA.API.Models.Domain.Entities;

namespace PIZZERIA.APP.Models
{
    public class PedidoViewModel
    {
        public int PedidoId { get; set; }
        public Pizza oPizza { get; set; }
        public Proceso oProceso { get; set; } = new Proceso();
    }
}

PIZZERIA.APP/Models/PizzaViewModel.cs
namespace PIZZERIA.APP.Models
{
    public class PizzaViewModel
    {
        public int PizzaId { get; set; }
        public string Denominacion { get; set; } = String.Empty;

        public List<IngredienteViewModel> Ingredientes { get; set; } = new List<IngredienteViewModel>();
    }
}

PIZZERIA.APP/Models/ProcesoViewModel.cs
namespace PIZZERIA.APP.Models
{
    public class ProcesoViewModel
    {
        public int ProcesoId { get; set; }
        public string Denominacion { get; set; } = String.Empty;
    }
}

PIZZERIA.APP/Controllers/PizzeriaClientController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using Newtonsoft.Json;
using PIZZERIA.APP.Models;
using PIZZERIA.API.Models.Domain.Entities;
using System.Text;

namespace PIZZERIA.APP.Controllers
{
    public class PizzeriaClientController : Controller
    {
        private readonly HttpClient _httpClient;

        public PizzeriaClientController(HttpClient httpClientFactory)
        {
            _httpClient = httpClientFactory;
            _httpClient.BaseAddress = new Uri("https://localhost:7188/api");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Ingredientes()
        {
            return View();
        }

        public IActionResult Pedidos()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> listarPizzas()
        {
            var response = await _httpClient.GetAsync("api/Pizzeria/Pizzas");
            var content = await response.Content.ReadAsStringAsync();
            var pizzas = JsonConvert.DeserializeObject<IEnumerable<PizzaViewModel>>(content);

            return StatusCode(StatusCodes.Status200OK, pizzas);
        }

        [HttpGet]
        public async Task<IActionResult> listarIngredientes()
        {
            var response = await _httpClient.GetAsync("api/Pizzeria/Ingredientes");
            var content = await response.Content.ReadAsStringAsync();
            var pizzas = JsonConvert.DeserializeObject<IEnumerable<IngredienteViewModel>>(content);

            return StatusCode(StatusCodes.Status200OK, pizzas);
        }

        [HttpGet]
        public async Task<IActionResult> listarIngredientesByPizza(int pizzaId)
        {
            var response = await _httpClient.GetAsync($"api/Pizzeria/IngredientesByPizza?pizzaId={pizzaId}");
            var content = await response.Content.ReadAsStringAsync();
            var ingredientes = JsonConvert.DeserializeObject<IEnumerable<IngredienteViewModel>>(content);

            return StatusCode(StatusCodes.Status200OK, ingredientes);
        }

        [HttpGet]
        public async Task<IActionResult> listarPedidos()
        {
            var response = await _httpClient.GetAsync("api/Pizzeria/Pedidos");
            var content = await response.Content.ReadAsStringAsync();
            var pizzas = JsonConvert.DeserializeObject<IEnumerable<PedidoViewModel>>(content);

            return StatusCode(StatusCodes.Status200OK, pizzas);
        }

        [HttpPost]
        public async Task<IActionResult> AddPedido([FromBody] Pizza pizza)
        {
           
                var json = JsonConvert.SerializeObject(pizza);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("api/Pizzeria/AddPedido", content);
                return StatusCode(StatusCodes.Status200OK);

        }

        [HttpPut]
        public async Task<IActionResult> EditPedido([FromBody] Pizza objpizza, int idpedido)
        {

            var json = JsonConvert.SerializeObject(objpizza);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"api/Pizzeria/EditPedido?pedidoId={idpedido}", content);
            return StatusCode(StatusCodes.Status200OK);

        }

        [HttpDelete]
        public async Task<IActionResult> CancelPedido(int idpedido)
        {
            var response = await _httpClient.DeleteAsync($"api/Pizzeria/CancelPedido?pedidoId={idpedido}");
            return StatusCode(StatusCodes.Status200OK);

        }

        [HttpGet]
        public async Task<IActionResult> ConsultarPedido(int idpedido)
        {
            var response = await _httpClient.GetAsync($"api/Pizzeria/ConsultarPedido?pedidoId={idpedido}");
            var content = await response.Content.ReadAsStringAsync();
            
            var pedido = JsonConvert.DeserializeObject<PedidoViewModel>(content);


            return StatusCode(StatusCodes.Status200OK,pedido);

        }
    }
}

PIZZERIA.APP/Views/PizzeriaClient/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="row justify-content-center">

    <div class="col-10">

        <div class="alert alert-info" role="alert">
            PIZZERIA BAMBINO
        </div>
        <a href="@Url.Action("Ingredientes","PizzeriaClient")" type="button" class="btn btn-primary btn-sm boton-nuevo-empleado">Ingredientes</a>
        <a href="@Url.Action("Pedidos","PizzeriaClient")" type="button" class="btn btn-primary btn-sm boton-nuevo-empleado">Pedidos</a>

        <table class="table table-striped" id="tablaPizzas">
            <thead>
                <tr>
                    <th>Tipo de Pizza</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


<div class="modal fade" id="formModalIngredientes" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="staticBackdropLabel">Ingredientes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <hr class="mt-2 mb-2">
                <div class="row py-3 px-4">
                    <div class="card mb-2 table-responsive shadow" id="card-ing" style="height: 300px;">
                        <div id="lista-ing">
                        </div>

                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert" hidden="true">
                            A simple Danger message
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script src="~/js/index.js"></script>
}

PIZZERIA.APP/Views/PizzeriaClient/Ingredientes.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="row justify-content-center">

    <div class="col-10">

        <div class="alert alert-info" role="alert">
            PIZZERIA BAMBINO
        </div>
        <a href="@Url.Action("Index","PizzeriaClient")" type="button" class="btn btn-primary btn-sm boton-nuevo-empleado">Volver</a>

        <table class="table table-striped" id="tablaIngredientes">
            <thead>
                <tr>
                    <th>Denominacion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


@section Scripts {
    <script src="~/js/index.js"></script>
}

PIZZERIA.APP/Views/PizzeriaClient/Pedidos.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="row justify-content-center">

    <div class="col-10">

        <div class="alert alert-info" role="alert">
            PIZZERIA BAMBINO
        </div>
        <a href="@Url.Action("Index","PizzeriaClient")" type="button" class="btn btn-primary btn-sm boton-nuevo-empleado">Volver</a>

        <table class="table table-striped" id="tablaPedidos">
            <thead>
                <tr>
                    <th>Id Pedido</th>
                    <th>Tipo de Pizza</th>
                    <th>Proceso</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

<div class="modal fade" id="formModalPizzas" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="staticBackdropLabel">Pizzas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                
                <hr class="mt-2 mb-2">
                <div class="row py-3 px-4">
                    <div class="card mb-2 table-responsive shadow" id="card-pizzas" style="height: 300px;">
                        <div id="lista-pizzas">
                            
                        </div>

                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert" hidden="true">
                            A simple Danger message
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalEmpleado" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal Empleado</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="mb-3">
                    <label class="form-label">Nombre Completo</label>
                    <input type="text" class="form-control" id="txtNombreCompleto" autocomplete="off">
                </div>

                <div class="mb-3">
                    <label class="form-label">Departamento</label>
                    <select class="form-select" id="cboDepartamento"></select>
                </div>

                <div class="mb-3">
                    <label class="form-label">Sueldo</label>
                    <input type="number" class="form-control" id="txtSueldo">
                </div>

                <div class="mb-3">
                    <label class="form-label">Fecha Contrato</label>
                    <input type="text" class="form-control" id="txtFechaContrato">
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary boton-guardar-cambios-empleado">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script src="~/js/index.js"></script>
}

PIZZERIA.APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PIZZERIA.APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PIZZERIA.APP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PIZZERIA.APP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PIZZERIA.APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>